### PR TITLE
fix: Escape `<` when serializing attribute values

### LINKED ISSUE #198: '<' and '>' are not escaped in attribute values
Serializer does not escape < and > characters in attribute values
`const doc = new DOMParser().parseFromString('<a a="&lt;&gt;"/>');`
`const result = new XMLSerializer().serializeToString(doc);`
result is `<a a="<>"/>`, which is invalid xml

### PR DESCRIPTION
**Pull request by karfau**
to produce well formed XML.

> Well-formedness constraint: No `<` in Attribute Values
> The replacement text of any entity referred to directly or indirectly in an attribute value must not contain a `<`.

https://www.w3.org/TR/xml/#CleanAttrVals
https://www.w3.org/TR/xml/#NT-AttValue

fixes #198

### CODE REVIEW

File: lib/dom.js [hunk 1]
```diff
@@ -1068,7 +1068,13 @@ function serializeToString(node,buf,isHTML,nodeFilter,visibleNamespaces){
...
 		return;
 	case ATTRIBUTE_NODE:
-		return buf.push(' ',node.name,'="',node.value.replace(/[&"]/g,_xmlEncoder),'"');
+		/**
+		 * Well-formedness constraint: No < in Attribute Values
+		 * The replacement text of any entity referred to directly or indirectly in an attribute value must not contain a <.
+		 * @see https://www.w3.org/TR/xml/#CleanAttrVals
+		 * @see https://www.w3.org/TR/xml/#NT-AttValue
+		 */
+		return buf.push(' ',node.name,'="',node.value.replace(/[<&"]/g,_xmlEncoder),'"');
```
Comment (brodybits) [inline lib/dom.js:1077]: minor nit, just a suggestion:

```suggestion
		return buf.push(' ', node.name, '="', node.value.replace(/[<&"]/g,_xmlEncoder), '"');
```

**Review by brodybits — APPROVED** [review]
