### PR TITLE
fix: parse empty/whitspace only doctype internal subset

### LINKED ISSUE #691: Doctypes without children are broken
**Describe the bug**
The following document can not be parsed:
`<!DOCTYPE root []><root></root>`

**To Reproduce**
Try to parse the document
`<!DOCTYPE root []><root></root>`

**Expected behavior**
It is possible to parse the document

**Runtime & Version:**
xmldom version: master
runtime version: -
other related software and version:  -

---

**I will create an PR for the fix.**

### PR DESCRIPTION
**Pull request by kpalatzky**
Added a condition to the parser to allow empty doctypes

### CODE REVIEW

**Comment by karfau** [comment]
Thank you for your contribution.
If the doctype decl would be `[]` the internalSubset would be an empty string, right?
Do you think it is worth adding another test case for that?

Once the formatting issue is fixed, I can land it.

**Comment by kpalatzky** [comment]
@karfau I added the test: https://github.com/xmldom/xmldom/pull/692/files#diff-7d53de1cebcbf7f6d753bd87ec5bd039dab2e818c406d35439c952419c1a2e42R125

**Comment by karfau** [comment]
Thx for adding the test.
Can you also fix the prettier issue by running `npm run format` and commiting and pushing the resulting changes?
Thx.

I will try to release a new version soon, potentially even 0.9.0

**Comment by kpalatzky** [comment]
@karfau I fixed the formatting. 

_BTW (Not replated to the PR but for 0.9.0): There is currently an typing issue with the DOMImplementation - Its definied as a type but need to bedefined as a class to use the "new" keyword_

File: lib/sax.js [hunk 1]
```diff
@@ -719,6 +719,10 @@ function parseDoctypeInternalSubset(p, errorHandler) {
 				current = parsePI(p, errorHandler);
 			} else if (p.char() === '%') {
 				current = p.getMatch(g.PEReference);
+			} else if (p.char() === ']') {
```
Comment (karfau) [inline lib/sax.js:722]: Once I'm back on my computer I will check if it can be refactored to avoid multiple occurrences of this condition, before landing it.

**Comment by karfau** [comment]
@kpalatzky for some reason I'm not able to push to the branch that you created to provide the changes.
Can you please enable the option for xmldom maintainers to push to this PR or apply the following [commit](https://github.com/xmldom/xmldom/commit/c4aaa1af7179876a56df58c4325fb58ef80cf6c3) to it?

**Review by karfau — APPROVED** [review]
